name: meal_app
description: A simple meal management starter app (Flutter + Firebase)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
